# Generated by Django 2.0.4 on 2018-05-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20180515_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('area', models.CharField(choices=[('all', 'All'), ('ML', 'MainLand'), ('HT', 'HongKong & TaiWan'), ('EA', 'European & American'), ('SK', 'South Korea'), ('JP', 'Japan')], max_length=50)),
                ('genre', models.CharField(choices=[('all', 'All'), ('pop', 'Pop'), ('rap', 'Rap'), ('hiphop', 'HipHop'), ('blues', 'Blues'), ('classic', 'Classic'), ('rock', 'Rock'), ('live', 'Live'), ('country', 'Country')], max_length=10)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('band', 'Band')], max_length=10)),
                ('artist_img', models.ImageField(default=None, upload_to='pics')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to='musics'),
        ),
    ]
