# Generated by Django 2.0.4 on 2018-05-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180524_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_img',
        ),
    ]
